% addpath('../SMGPC','../Netlab3_3','../FGPLVM','../GP','../KERN0p225','../OPTIMI0p132','../NDLUTIL0p162','../MLTOOLS0p135','../MOCAP0p136','../PRIOR0p22','../NOISE0p141','../DATASETS0p1371','../../../DataSets/OtherDatasets','../../knn')
addpath('netlab3_3','FGPLVM','GP','KERN0p225','NDLUTIL0p162','MLTOOLS0p135','OPTIMI0p132','../knn','../DataSets/Face',...
    '../DataSets/OtherDatasets','../DataSets/UCI/Classification/Ionosphere',...
    '../DataSets/UCI/Classification/IRIS','../DataSets/UCI/Classification/Sonar',...
    '../DataSets/UCI/Classification/Wine','../DataSets/UCI/Classification',...
    '../DataSets/UCI/Regression');